# Generated by Django 3.1.1 on 2020-09-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0002_auto_20200930_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Shirts', 'SH'), ('Sport Wears', 'SW'), ('Out Wears', 'OW')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_state',
            field=models.CharField(blank=True, choices=[('New', 'N'), ('Bestseller', 'BS')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('primary', 'P'), ('secondary', 'S'), ('danger', 'D')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='Ecom.OrderItem'),
        ),
    ]
