# Generated by Django 3.1.1 on 2020-10-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0008_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='countries',
            new_name='country',
        ),
    ]
