# Generated by Django 3.1.1 on 2020-10-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0011_auto_20201003_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='static/img/default.jpg', null=True, upload_to='item_images/'),
        ),
    ]
