# Generated by Django 3.1.1 on 2020-10-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0014_auto_20201003_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='item_images'),
        ),
    ]
