# Generated by Django 3.1.1 on 2020-10-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0019_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='payment_option',
            field=models.CharField(choices=[('P', 'PayPal'), ('S', 'Stripe')], max_length=1, null=True),
        ),
    ]
