# Generated by Django 3.1.1 on 2020-10-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0020_shippingaddress_payment_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='payment_option',
        ),
    ]
